export default {
  HERO_ID_NOT_FOUND: '1000',
  HERO_CANT_FIGHT_SAME_HERO: '1001',
  HERO_PARAMETER_MANDATORY: '1002',
  MAX_HERO_REACHED_IN_FIGHT: '1003',
  FIGHT_COULDNT_START_NO_HEROES: '1004',
};
